name: Publish StaxDB to NPM

on:
  push:
    branches:
      - 'release-test' # Trigger on pushes to the 'release-test' branch for iterative testing
    # tags:
    #   - 'v*.*.*' # Uncomment this for actual release publishing

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: windows-latest
            arch: x64
          - os: macos-latest # This will run on an x64 runner
            arch: x64
          - os: macos-latest # We will cross-compile for arm64 on the x64 runner
            arch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install C++ build tools (Linux)
        if: runner.os == 'Linux'
        # !!! BUG FIX !!! Added libboost-all-dev to install the required Boost libraries for the C++ benchmark.
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libboost-all-dev

      - name: Install C++ build tools (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Install C++ build tools (macOS)
        if: runner.os == 'macOS'
        # !!! BUG FIX !!! Added boost to the brew install command.
        run: brew install cmake boost
      
      - name: Build C++ executables
        shell: bash
        run: |
          set -e
          echo "--- Building C++ binaries with CMake ---"
          mkdir -p build/release
          cd build/release
          cmake ../.. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          echo "--- C++ binaries built successfully ---"
          ls -l ../../bin/

      - name: Run C++ Benchmarks
        shell: bash
        run: |
          echo "--- Running C++ stax_benchmark executable ---"
          ./bin/stax_benchmark

      - name: Build native addon
        id: build_addon
        shell: bash
        run: |
          set -e
          cd stax_js

          echo "--- Installing Node.js dependencies ---"
          npm install --ignore-scripts

          echo "--- Compiling native addon for ${{ matrix.os }}-${{ matrix.arch }} ---"
          if [[ "${{ runner.os }}" == "macOS" && "${{ matrix.arch }}" == "arm64" ]]; then
            npm exec -- node-gyp rebuild --arch=arm64 --target_arch=arm64
          else
            npm exec -- node-gyp rebuild
          fi

      - name: Run Node.js Tests
        shell: bash
        run: |
          echo "--- Running Node.js test suite ---"
          cd stax_js
          npm test

      - name: Run Node.js Benchmarks
        shell: bash
        run: |
          echo "--- Running Node.js benchmark suite ---"
          cd stax_js
          npm run bench

      - name: Stage binary for artifact upload
        shell: bash
        run: |
          echo "--- Staging pre-built binary ---"
          PLATFORM_DIR=""
          if [[ "${{ runner.os }}" == "Linux" ]]; then
              PLATFORM_DIR="linux-x64"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
              PLATFORM_DIR="win32-x64"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
              PLATFORM_DIR="darwin-${{ matrix.arch }}"
          fi
          
          mkdir -p prebuilds-staging/${PLATFORM_DIR}
          cp stax_js/build/Release/staxdb.node prebuilds-staging/${PLATFORM_DIR}/staxdb.node
          echo "Binary staged to prebuilds-staging/${PLATFORM_DIR}/staxdb.node"

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-${{ matrix.os }}-${{ matrix.arch }}
          path: prebuilds-staging/

  publish:
    name: Publish to NPM
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Download all binary artifacts
        uses: actions/download-artifact@v4
        with:
          path: prebuilds-all/
      
      - name: Prepare package for publishing
        shell: bash
        run: |
          set -e
          echo "--- Consolidating pre-built binaries ---"
          mkdir -p stax_js/prebuilds
          
          find prebuilds-all -type f -name 'staxdb.node' -exec sh -c ' \
            PLATFORM_OS_ARCH=$(basename $(dirname $(dirname {}))); \
            PLATFORM_OS_ARCH=${PLATFORM_OS_ARCH#prebuilds-}; \

            DEST_PLATFORM=""; \
            if [[ "$PLATFORM_OS_ARCH" == "ubuntu-latest-x64" ]]; then \
              DEST_PLATFORM="linux-x64"; \
            elif [[ "$PLATFORM_OS_ARCH" == "windows-latest-x64" ]]; then \
              DEST_PLATFORM="win32-x64"; \
            elif [[ "$PLATFORM_OS_ARCH" == "macos-latest-x64" ]]; then \
              DEST_PLATFORM="darwin-x64"; \
            elif [[ "$PLATFORM_OS_ARCH" == "macos-latest-arm64" ]]; then \
              DEST_PLATFORM="darwin-arm64"; \
            else \
              echo "Unknown platform-arch: $PLATFORM_OS_ARCH. Copying as is."; \
              DEST_PLATFORM="$PLATFORM_OS_ARCH"; \
            fi; \
            
            DEST_DIR="stax_js/prebuilds/$DEST_PLATFORM"; \
            mkdir -p "$DEST_DIR"; \
            cp "$1" "$DEST_DIR/staxdb.node"; \
            echo "Copied $1 to $DEST_DIR/staxdb.node"; \
          ' sh {} \;
          
          echo "--- Final prebuilds directory structure ---"
          ls -R stax_js/prebuilds
          
          echo "--- Installing dependencies for publishing ---"
          cd stax_js
          npm install --ignore-scripts


      - name: Publish to NPM
        run: |
          cd stax_js
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}